### ISSUE TITLE
Maximum call stack

### ISSUE THREAD

**Issue by simon-p-r** [simon-p-r/yajsv#10]
This bug occurs when record type and definition share same filename namespace

````js


RangeError: Maximum call stack size exceeded
    at Number.toString (native)
    at collectReferences (D:\Modules\yajsv\node_modules\z-schema\src\SchemaCompilation.js:71:27)
    at collectReferences (D:\Modules\yajsv\node_modules\z-schema\src\SchemaCompilation.js:82:13)
    at collectReferences (D:\Modules\yajsv\node_modules\z-schema\src\SchemaCompilation.js:82:13)
    at collectReferences (D:\Modules\yajsv\node_modules\z-schema\src\SchemaCompilation.js:82:13)
    at collectReferences (D:\Modules\yajsv\node_modules\z-schema\src\SchemaCompilation.js:82:13)
    at collectReferences (D:\Modules\yajsv\node_modules\z-schema\src\SchemaCompilation.js:82:13)
    at collectReferences (D:\Modules\yajsv\node_modules\z-schema\src\SchemaCompilation.js:82:13)
    at collectReferences (D:\Modules\yajsv\node_modules\z-schema\src\SchemaCompilation.js:82:13)
    at collectReferences (D:\Modules\yajsv\node_modules\z-schema\src\SchemaCompilation.js:82:13)
````

**Comment by simon-p-r** [comment]
Closed by b60cbd5232b05a192212b49b52a32d17b770a7ca
